### PR TITLE
Fix compatibility with older browsers in zxing-js

### PR DESCRIPTION
**Pull request by bilal-elchami**
This PR fixes the described bug in this issue: https://github.com/mebjas/html5-qrcode/issues/188

@all-contributors please add @bilal-elchami for this feature.

### CODE REVIEW

**Comment by mebjas** [comment]
Thanks for the change -- merging.

**Comment by JL102** [comment]
@mebjas This change breaks html5-qrcode in modern browsers. Tested on Vivaldi 5.7.2921.63 (using V8 11.0.226.19) and Firefox 111.0. Built from source on Ubuntu and imported into a Svelte project to test.

image
image

**Comment by bilal-elchami** [comment]
> @mebjas This change breaks html5-qrcode in modern browsers. Tested on Vivaldi 5.7.2921.63 (using V8 11.0.226.19) and Firefox 111.0. Built from source on Ubuntu and imported into a Svelte project to test.
> 
> image image

@JL102  Sorry to hear this. I will try to find a fix by the end of the day.

**Comment by mebjas** [comment]
I am reverting this by another PR for now (https://github.com/mebjas/html5-qrcode/pull/738)

@bilal-elchami if you have a non breaking change later - please send another PR.

**Comment by mebjas** [comment]
@JL102 thanks for sharing the issue.

**Comment by JL102** [comment]
@mebjas np. Try this instead:

```js
const g = (typeof globalThis !== 'undefined') ? globalThis :
    (typeof global !== 'undefined') ? global :
    (typeof self !== 'undefined') ? self :
    (typeof window !== 'undefined') ? window : {};
var __awaiter = g.__awaiter || function ( .....
```
The typeof operator allows non declared variables.

**Comment by khata-anshul** [comment]
Can we get these changes merged please - https://github.com/mebjas/html5-qrcode/pull/700#issuecomment-1507716986 

v2.3.8 is still throwing `globalThis is not defined` error -

**Comment by axylophon** [comment]
This would be really nice as we are currently blocked with anything below Android 10...

**Pull request merged**
