### PR TITLE
Use ES6 import/export statements in original JS files, modify build scripts to avoid redundant code snippets

### PR DESCRIPTION
**Pull request by georgewei**
There are two main changes:
1.Use ES6 import/export statements in original JS files, so they can be imported into an ES6 project;
2.Modify build scripts to avoid redundant code snippets in minified code. The idea is concatenating all source files into a temporary file & removing import/export key words before transpiling.

The minified code still can not be imported into ES6 project.

### CODE REVIEW

**Review by georgewei — COMMENTED** [review]
@mebjas Please check this PR.

**Comment by Vincz** [comment]
Thanks @georgewei !
@mebjas Any ETA for this PR to be merged? Thx !

**Comment by domiSchenk** [comment]
@mebjas whats the status of this PR?

**Comment by mebjas** [comment]
I have migrated the code to Typescript now, now we should be able to just write a separate typescirpt config to generate JavaScript code compatible with different loaders.

**Comment by mebjas** [comment]
Closing this as obsolete

**Pull request closed without merging**
